language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services

notifications:
  email: false

before_install:
 - chmod +x gradlew

script: ./gradlew clean
